services:
  reviewbot:
    image: ghcr.io/iostpa/reviewbot:latest
    restart: always
    env_file: ".env"
    ports:
      - "3000:3000"
    volumes:
      - ./private-key.pem:/app/private-key.pem:ro  # read-only